package rules;
dialect  "mvel"

import java.util.ArrayList;
import rushB.CS.GO.Buy.Recommender.facts.Armament;
import rushB.CS.GO.Buy.Recommender.facts.ArmamentType;
import rushB.CS.GO.Buy.Recommender.facts.Side;
import rushB.CS.GO.Buy.Recommender.facts.Player;
import rushB.CS.GO.Buy.Recommender.dtos.RoundInput;
import rushB.CS.GO.Buy.Recommender.facts.Player;
import rushB.CS.GO.Buy.Recommender.facts.Rank;
import rushB.CS.GO.Buy.Recommender.facts.Tactic;
import rushB.CS.GO.Buy.Recommender.facts.BuyOptions;
import rushB.CS.GO.Buy.Recommender.facts.Map;
import rushB.CS.GO.Buy.Recommender.facts.Round;
import rushB.CS.GO.Buy.Recommender.facts.PlayerStatus;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import rushB.CS.GO.Buy.Recommender.facts.Weapon;

global HashMap<String, Armament> armaments;
global Map map;
global HashMap<String, Player> players;

rule "Teammates' rank is lower than DMG first round"
    when
        Integer( this == 1 || this == 16, $rn: this )
        Player( $name: name, rank < Rank.DISTINGUISHED_MASTER_GUARDIAN )
        $ps: PlayerStatus( player == $name, cash == 800, round == $rn )
        List( size == 5 ) from collect(Player( rank < Rank.DISTINGUISHED_MASTER_GUARDIAN ))
    then
        Armament kevlar = (Armament) armaments.get("Kevlar");

        Integer newCash = $ps.getCash() - kevlar.getPrice();
        modify($ps) { setCash(newCash) }

        kevlar.setPlayerStatus($ps.getId());
        insert(kevlar)

        System.out.println(String.format("Bought %s for %s", kevlar.getName(), $name));
end


rule "Determine team state"
    when
        Integer( this != 1 && this != 16, $rn: this )
        $r: Round( currentTeamState == null, number == $rn )
    then
end


rule "Determine if ECO" extends "Determine team state"
    when
        exists(PlayerStatus( cash < 3000, round == $rn ))
        $p: PlayerStatus(round == $rn)
    then
        modify($r){ setCurrentTeamState(BuyOptions.ECO) }
        System.out.println("Team should go ECO");
end


rule "Determine if HALF BUY" extends "Determine team state"
    when
        exists(PlayerStatus( cash >= 3000 && cash < 4000, round == $rn ))
        forall(
            PlayerStatus( cash >= 3000 && cash < 4000, round == $rn )
        )
    then
        modify($r){ setCurrentTeamState(BuyOptions.HALF_BUY) }
        System.out.println("Team should go HALF BUY");
end

rule "Determine if FULL BUY" extends "Determine team state"
    when
        exists(PlayerStatus( cash >= 4000, round == $rn ))
        forall(
            PlayerStatus( cash >= 4000, round == $rn )
        )
    then
        modify($r){ setCurrentTeamState(BuyOptions.FULL_BUY) }
        System.out.println("Team should go FULL BUY");
end

/*
rule "Buy kevlar if not ECO or first round"
    when
        eval(currentRound != 1 && currentRound != 16)
        Round( currentTeamState != null && currentTeamState != BuyOptions.ECO, number == currentRound )
        $p: Player ( )
        $ps: PlayerStatus( player == $p.getName(), round == currentRound )
        not Armament( name == "Kevlar" || name == "Kevlar + Helmet", playerStatus == $ps.getId())
    then
        Armament kevlar = (Armament) armaments.get("Kevlar");

        Integer newCash = $ps.getCash() - kevlar.getPrice();
        modify($ps) { setCash(newCash) }

        kevlar.setPlayerStatus($ps.getId());
        insert(kevlar);

        System.out.println(String.format("Bought Kevlar for %s", $p.getName()));
end
*/


/*
rule "Buy helmet if kevlar is bought and not ECO or first round"
    when
        $ri: RoundInput( currentTeamState != null && currentTeamState != BuyOptions.ECO , currentRound != 1 &&
        currentRound != 16, $teammates: players )
        $p: Player( $a: armaments ) from $teammates
        exists(Armament( name == "Kevlar") from $a.list)
    then
        Armament kevlarHelmet = (Armament) armaments.get("Kevlar + Helmet");
        Armament kevlar = (Armament) armaments.get("Kevlar");

        $p.setCash($p.getCash() - 350);

        $p.getArmaments().getList().remove(kevlar);
        $p.getArmaments().getList().add(kevlarHelmet);
        update($ri);

        System.out.println(String.format("Bought Helmet for %s", $p.getName()));
end

rule "Buy p250 Eco round CT for map CACHE"
    when
        $ri: RoundInput(currentTeamState == BuyOptions.ECO, tactic == Tactic.OFFENSIVE,
                        teamSide == Side.COUNTER_TERRORIST, map == Map.CACHE, $teammates: players )
        $p: Player( $a: armaments ) from $teammates
        exists(Armament( name == "USP-S" ) from $a.list)
    then
        Armament p250 = (Armament) armaments.get("P250");
        Armament usp = (Armament) armaments.get("USP-S");

        $p.setCash($p.getCash() - p250.getPrice());
        $p.getArmaments().getList().remove(usp);
        $p.getArmaments().getList().add(p250);
        update($ri)

        System.out.println(String.format("Bought P250 for %s", $p.getName()));
end

rule "Buy SMG's for Half buy round CT for map CACHE"
    when
        $ri: RoundInput(currentTeamState == BuyOptions.HALF_BUY, tactic == Tactic.OFFENSIVE,
                        teamSide == Side.COUNTER_TERRORIST, map == Map.CACHE, $teammates: players)
        $p: Player ( $a: armaments ) from $teammates
        forall(
               Armament( type != ArmamentType.SMG
                         && type != ArmamentType.HEAVY
                         && type != ArmamentType.RIFLE) from $a.list
         )
    then
        Armament mp9 = (Armament) armaments.get("MP-9");
        $p.setCash($p.getCash() - mp9.getPrice());
        $p.getArmaments().getList().add(mp9);
        update($ri)

        System.out.println(String.format("Bought MP-9 for %s", $p.getName()));
end

rule "Buy Rifle's for Full buy round CT for map CACHE"
    when
        $ri: RoundInput(currentTeamState == BuyOptions.FULL_BUY, tactic == Tactic.OFFENSIVE,
                        teamSide == Side.COUNTER_TERRORIST, map == Map.CACHE, $teammates: players)
        $p: Player ( $a: armaments ) from $teammates
        forall(
               Armament(type != ArmamentType.RIFLE) from $a.list
         )
    then
        Armament m4 = (Armament) armaments.get("M4A4");
        $p.setCash($p.getCash() - m4.getPrice());
        $p.getArmaments().getList().add(m4);
        update($ri)

        System.out.println(String.format("Bought M4A4 for %s", $p.getName()));
end

rule "Buy TEC-9 Eco round T for map CACHE"
    when
        $ri: RoundInput(currentTeamState == BuyOptions.ECO, tactic == Tactic.OFFENSIVE,
                        teamSide == Side.TERRORIST, map == Map.CACHE, $teammates: players )
        $p: Player( $a: armaments ) from $teammates
        exists(Armament( name == "Glock-18" ) from $a.list)
    then
        Armament tec9 = (Armament) armaments.get("Tec-9");
        Armament glock = (Armament) armaments.get("Glock-18");

        $p.setCash($p.getCash() - tec9.getPrice());
        $p.getArmaments().getList().remove(glock);
        $p.getArmaments().getList().add(tec9);
        update($ri)

        System.out.println(String.format("Bought Tec-9 for %s", $p.getName()));
end

rule "Buy MAC-10 Half buy round T for map CACHE"
    when
        $ri: RoundInput(currentTeamState == BuyOptions.HALF_BUY, tactic == Tactic.OFFENSIVE,
                        teamSide == Side.TERRORIST, map == Map.CACHE, $teammates: players )
        $p: Player( $a: armaments ) from $teammates
                forall(
                       Armament( type != ArmamentType.SMG
                                 && type != ArmamentType.HEAVY
                                 && type != ArmamentType.RIFLE) from $a.list
                 )
    then
        Armament mac = (Armament) armaments.get("MAC-10");

        $p.setCash($p.getCash() - mac.getPrice());
        $p.getArmaments().getList().add(mac);
        update($ri)

        System.out.println(String.format("Bought MAC-10 for %s", $p.getName()));
end

rule "Buy Rifle's for Full buy round T for map CACHE"
    when
        $ri: RoundInput(currentTeamState == BuyOptions.FULL_BUY, tactic == Tactic.OFFENSIVE,
                        teamSide == Side.TERRORIST, map == Map.CACHE, $teammates: players)
        $p: Player ( $a: armaments ) from $teammates
        forall(
               Armament(type != ArmamentType.RIFLE) from $a.list
         )
    then
        Armament ak = (Armament) armaments.get("AK-47");
        $p.setCash($p.getCash() - ak.getPrice());
        $p.getArmaments().getList().add(ak);
        update($ri)

        System.out.println(String.format("Bought AK-47 for %s", $p.getName()));
end
*/
